#' Render the screening report as a self-contained HTML document
#'
#' Builds a single self-contained HTML file from whatever project
#' artefacts are supplied and returns the path to it. Open it in a
#' browser to view; use the browser's Print > Save as PDF to archive as
#' PDF (this avoids the LaTeX install that a direct PDF backend would
#' need).
#'
#' All artefact arguments default to `NULL`; the report fills in "(not
#' recorded)" for anything missing, so the same call works whether the
#' reviewer is midway through screening or fully finished.
#'
#' @param output_file Path to write the HTML report to. Defaults to a
#'   file in `tempdir()`.
#' @param project Optional project name (for the report header).
#' @param ranked Optional ranked corpus tibble.
#' @param plan Optional `screenllm_plan` object.
#' @param decisions Optional tibble of human decisions.
#' @param criteria Optional `screenllm_criteria` object.
#' @param ensemble Optional `screenllm_ensemble` object.
#' @return Invisibly, the path to the rendered HTML file.
#' @export
#' @examples
#' \dontrun{
#' path <- export_report(project = "my-review",
#'                       ranked = load_artefact("my-review", "ranked"),
#'                       plan = load_artefact("my-review", "plan"),
#'                       decisions = load_artefact("my-review", "decisions"))
#' utils::browseURL(path)
#' }
export_report <- function(output_file = NULL,
                          project = NULL,
                          ranked = NULL,
                          plan = NULL,
                          decisions = NULL,
                          criteria = NULL,
                          ensemble = NULL) {
  if (is.null(output_file)) {
    output_file <- tempfile(fileext = ".html")
  }

  version <- tryCatch(
    as.character(utils::packageVersion("screenllm")),
    error = function(e) ""
  )
  header <- paste0(
    "<p><strong>Project:</strong> ",
    report_escape(if (is.null(project)) "(unnamed)" else project), "<br>\n",
    "<strong>Generated:</strong> ",
    report_escape(format(Sys.time(), "%Y-%m-%d %H:%M %Z")), "<br>\n",
    "<strong>Package:</strong> screenllm ", report_escape(version), "</p>"
  )

  sections <- list(
    c("Ensemble",                          report_ensemble_html(ensemble)),
    c("Inclusion criteria",                report_criteria_html(criteria)),
    c("SAFE plan",                         report_pre(plan)),
    c("Ranking summary",                   report_ranking_html(ranked)),
    c("Human decisions",                   report_decisions_html(decisions)),
    c("Screening summary",                 report_summary_html(ranked, decisions, plan)),
    c("Strong LLM-vs-human disagreements", report_audit_html(ranked, decisions))
  )
  ids <- vapply(sections, function(s) report_anchor(s[[1]]), character(1))

  toc <- paste0(
    "<nav class=\"toc\"><strong>Contents</strong><ul>",
    paste0(
      "<li><a href=\"#", ids, "\">", report_escape(vapply(sections, `[[`, character(1), 1)),
      "</a></li>",
      collapse = ""
    ),
    "</ul></nav>"
  )

  body <- paste0(
    vapply(seq_along(sections), function(i) {
      paste0(
        "<section><h2 id=\"", ids[i], "\">",
        report_escape(sections[[i]][[1]]), "</h2>\n",
        sections[[i]][[2]], "\n</section>"
      )
    }, character(1)),
    collapse = "\n"
  )

  html <- paste0(
    "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n",
    "<meta charset=\"utf-8\">\n",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n",
    "<title>screenllm screening report</title>\n",
    "<style>\n", report_css(), "\n</style>\n",
    "</head>\n<body>\n",
    "<h1>screenllm screening report</h1>\n",
    header, "\n",
    toc, "\n",
    body, "\n",
    "<hr>\n<p class=\"footer\"><em>Generated by <code>screenllm::export_report()</code>. ",
    "To save as PDF, use your browser's Print &gt; Save as PDF.</em></p>\n",
    "</body>\n</html>\n"
  )

  writeLines(html, output_file, useBytes = TRUE)
  invisible(output_file)
}

# ---- HTML building blocks -----------------------------------------------

#' @keywords internal
report_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub("\"", "&quot;", x, fixed = TRUE)
  x
}

#' @keywords internal
report_anchor <- function(title) {
  a <- tolower(title)
  a <- gsub("[^a-z0-9]+", "-", a)
  gsub("^-|-$", "", a)
}

# A missing/empty section renders a muted placeholder.
#' @keywords internal
report_none <- function(msg) {
  paste0("<p class=\"muted\"><em>", report_escape(msg), "</em></p>")
}

# Capture an object's print() output verbatim inside a <pre> block. This
# reuses the package's existing print methods (plan, report, tables) so
# the HTML report stays in step with what those objects show at the
# console. The cli-based print methods write to the message stream while
# base print() (e.g. tables) writes to stdout, so capture both, and strip
# any ANSI styling cli may emit.
#' @keywords internal
report_pre <- function(obj) {
  if (is.null(obj)) return(report_none("(Not recorded.)"))
  msg <- NULL
  out <- utils::capture.output(
    msg <- utils::capture.output(print(obj), type = "message"),
    type = "output"
  )
  txt <- paste(cli::ansi_strip(c(out, msg)), collapse = "\n")
  paste0("<pre>", report_escape(txt), "</pre>")
}

#' @keywords internal
report_ensemble_html <- function(ensemble) {
  if (is.null(ensemble)) return(report_none("(No ensemble configuration recorded.)"))
  meta <- paste0(
    "<ul>",
    "<li><strong>Aggregator:</strong> ", report_escape(ensemble$aggregator), "</li>",
    "<li><strong>Replicates per model:</strong> ", report_escape(ensemble$replicates), "</li>",
    "<li><strong>Temperature:</strong> ", report_escape(ensemble$temperature), "</li>",
    "<li><strong>Backend:</strong> ", report_escape(ensemble$backend$name), "</li>",
    "</ul>"
  )
  models <- paste0(
    "<p><strong>Models:</strong></p><ul>",
    paste0("<li>", report_escape(ensemble$models), "</li>", collapse = ""),
    "</ul>"
  )
  paste0(meta, models)
}

#' @keywords internal
report_criteria_html <- function(criteria) {
  if (is.null(criteria)) return(report_none("(No criteria recorded.)"))
  scope <- paste0("<p><strong>Scope:</strong> ", report_escape(criteria$scope), "</p>")
  items <- paste0(
    "<p><strong>Criteria:</strong></p><ol>",
    paste0("<li>", report_escape(criteria$inclusions), "</li>", collapse = ""),
    "</ol>"
  )
  paste0(scope, items)
}

#' @keywords internal
report_ranking_html <- function(ranked) {
  if (is.null(ranked)) return(report_none("(No ranking recorded.)"))
  out <- paste0("<p>Records ranked: ", report_escape(nrow(ranked)), "</p>")
  if ("universal_best_score" %in% names(ranked)) {
    rng <- sprintf(
      "%.1f - %.1f",
      min(ranked$universal_best_score, na.rm = TRUE),
      max(ranked$universal_best_score, na.rm = TRUE)
    )
    out <- paste0(out, "<p>Score range: ", report_escape(rng), "</p>")
  }
  out
}

#' @keywords internal
report_decisions_html <- function(decisions) {
  if (is.null(decisions)) return(report_none("(No decisions recorded yet.)"))
  tbl <- table(decisions$human_decision, useNA = "ifany")
  paste0(
    report_pre(tbl),
    "<p>Total decisions: ", report_escape(nrow(decisions)), "</p>"
  )
}

#' @keywords internal
report_summary_html <- function(ranked, decisions, plan) {
  if (is.null(ranked) || is.null(decisions)) {
    return(report_none("(Need both ranking and decisions to compute summary.)"))
  }
  report_pre(summarise_screening(ranked, decisions, plan = plan))
}

#' @keywords internal
report_audit_html <- function(ranked, decisions) {
  intro <- paste0(
    "<p>Records where the LLM ensemble and the human reviewer disagreed ",
    "most strongly. Useful for a final audit pass, and per the paper's ",
    "finding, these are worth double-checking as they can flag ",
    "human-labelling errors.</p>"
  )
  if (is.null(ranked) || is.null(decisions)) {
    return(paste0(intro, report_none("(Need both ranking and decisions to run audit.)")))
  }
  aud <- audit_disagreements(ranked, decisions)
  if (nrow(aud) == 0L) {
    return(paste0(intro, "<p>No strong disagreements identified.</p>"))
  }
  keep <- intersect(
    c("id", "title", "universal_best_score", "human_decision", "disagreement"),
    names(aud)
  )
  paste0(intro, report_table_html(aud[, keep, drop = FALSE]))
}

# Render a data frame as a plain HTML table.
#' @keywords internal
report_table_html <- function(df) {
  head_row <- paste0(
    "<tr>", paste0("<th>", report_escape(names(df)), "</th>", collapse = ""), "</tr>"
  )
  body_rows <- vapply(seq_len(nrow(df)), function(i) {
    cells <- vapply(df[i, , drop = FALSE], function(v) report_escape(v), character(1))
    paste0("<tr>", paste0("<td>", cells, "</td>", collapse = ""), "</tr>")
  }, character(1))
  paste0("<table><thead>", head_row, "</thead><tbody>",
         paste0(body_rows, collapse = ""), "</tbody></table>")
}

#' @keywords internal
report_css <- function() {
  paste(
    "body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;",
    "line-height:1.5;color:#24292f;max-width:52rem;margin:2rem auto;padding:0 1rem;}",
    "h1{font-size:1.6rem;border-bottom:1px solid #d0d7de;padding-bottom:.3rem;}",
    "h2{font-size:1.25rem;margin-top:2rem;border-bottom:1px solid #eaecef;padding-bottom:.2rem;}",
    "nav.toc{background:#f6f8fa;border:1px solid #d0d7de;border-radius:6px;padding:.5rem 1rem;}",
    "nav.toc ul{margin:.3rem 0;padding-left:1.2rem;}",
    "pre{background:#f6f8fa;border-radius:6px;padding:.8rem;overflow-x:auto;",
    "font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.85rem;}",
    "table{border-collapse:collapse;width:100%;font-size:.9rem;}",
    "th,td{border:1px solid #d0d7de;padding:.4rem .6rem;text-align:left;vertical-align:top;}",
    "th{background:#f6f8fa;}",
    ".muted{color:#57606a;}",
    ".footer{color:#57606a;font-size:.85rem;}",
    sep = ""
  )
}
